// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: api/merge_log.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MergelogService_Post_FullMethodName                 = "/k8scpdt.mergelog.v1.MergelogService/Post"
	MergelogService_GetAllMergelogs_FullMethodName      = "/k8scpdt.mergelog.v1.MergelogService/GetAllMergelogs"
	MergelogService_GetRelevantMergelogs_FullMethodName = "/k8scpdt.mergelog.v1.MergelogService/GetRelevantMergelogs"
)

// MergelogServiceClient is the client API for MergelogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MergelogServiceClient interface {
	Post(ctx context.Context, in *MergelogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAllMergelogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Mergelogs, error)
	GetRelevantMergelogs(ctx context.Context, in *CPID, opts ...grpc.CallOption) (*Mergelogs, error)
}

type mergelogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMergelogServiceClient(cc grpc.ClientConnInterface) MergelogServiceClient {
	return &mergelogServiceClient{cc}
}

func (c *mergelogServiceClient) Post(ctx context.Context, in *MergelogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MergelogService_Post_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergelogServiceClient) GetAllMergelogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Mergelogs, error) {
	out := new(Mergelogs)
	err := c.cc.Invoke(ctx, MergelogService_GetAllMergelogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergelogServiceClient) GetRelevantMergelogs(ctx context.Context, in *CPID, opts ...grpc.CallOption) (*Mergelogs, error) {
	out := new(Mergelogs)
	err := c.cc.Invoke(ctx, MergelogService_GetRelevantMergelogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergelogServiceServer is the server API for MergelogService service.
// All implementations must embed UnimplementedMergelogServiceServer
// for forward compatibility
type MergelogServiceServer interface {
	Post(context.Context, *MergelogRequest) (*emptypb.Empty, error)
	GetAllMergelogs(context.Context, *emptypb.Empty) (*Mergelogs, error)
	GetRelevantMergelogs(context.Context, *CPID) (*Mergelogs, error)
	mustEmbedUnimplementedMergelogServiceServer()
}

// UnimplementedMergelogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMergelogServiceServer struct {
}

func (UnimplementedMergelogServiceServer) Post(context.Context, *MergelogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedMergelogServiceServer) GetAllMergelogs(context.Context, *emptypb.Empty) (*Mergelogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMergelogs not implemented")
}
func (UnimplementedMergelogServiceServer) GetRelevantMergelogs(context.Context, *CPID) (*Mergelogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRelevantMergelogs not implemented")
}
func (UnimplementedMergelogServiceServer) mustEmbedUnimplementedMergelogServiceServer() {}

// UnsafeMergelogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MergelogServiceServer will
// result in compilation errors.
type UnsafeMergelogServiceServer interface {
	mustEmbedUnimplementedMergelogServiceServer()
}

func RegisterMergelogServiceServer(s grpc.ServiceRegistrar, srv MergelogServiceServer) {
	s.RegisterService(&MergelogService_ServiceDesc, srv)
}

func _MergelogService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergelogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergelogServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergelogService_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergelogServiceServer).Post(ctx, req.(*MergelogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergelogService_GetAllMergelogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergelogServiceServer).GetAllMergelogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergelogService_GetAllMergelogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergelogServiceServer).GetAllMergelogs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MergelogService_GetRelevantMergelogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CPID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergelogServiceServer).GetRelevantMergelogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergelogService_GetRelevantMergelogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergelogServiceServer).GetRelevantMergelogs(ctx, req.(*CPID))
	}
	return interceptor(ctx, in, info, handler)
}

// MergelogService_ServiceDesc is the grpc.ServiceDesc for MergelogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MergelogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8scpdt.mergelog.v1.MergelogService",
	HandlerType: (*MergelogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _MergelogService_Post_Handler,
		},
		{
			MethodName: "GetAllMergelogs",
			Handler:    _MergelogService_GetAllMergelogs_Handler,
		},
		{
			MethodName: "GetRelevantMergelogs",
			Handler:    _MergelogService_GetRelevantMergelogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/merge_log.proto",
}
